apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-beer-horoscope-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: beer-rec-rest-api
  - name: git-url
    value: https://github.com/beer-horoscope/beer-horoscope-api.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/beer-rec-system/beer-rec-rest-api
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
